XCOPY "%OPENCV_DIR%/modules/core/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/video/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/imgproc/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/features2d/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/flann/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/calib3d/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/objdetect/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/legacy/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 
XCOPY "%OPENCV_DIR%/modules/highgui/include" "%OPENCV_DIR%/include " /D /E /C /R /I /K /Y 